### ISSUE TITLE
content `fmt-sidebars` converts tag to `unknown`

### ISSUE THREAD

**Issue by bsmth** [mdn/rari#221]
### What information was incorrect, unhelpful, or incomplete?

If I define a new page type in content to filter listsubpages, the `fmt-sidebars` command converts it to `unknown`.

Reproduce:

```yaml
  - type: listSubPages
    path: /Mozilla/Firefox/Releases
    tags: some-new-page-type
```

Run `yarn content fmt-sidebars`:

```yaml
  - type: listSubPages
    path: /Mozilla/Firefox/Releases
    tags: unknown
```

### What did you expect to see?

```yaml
  - type: listSubPages
    path: /Mozilla/Firefox/Releases
    tags: some-new-page-type
```

### Do you have any supporting links, references, or citations?

- [x] https://github.com/mdn/content/pull/39761
